version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - ${PWD}:/home/app/
      - /home/app/node_modules
    ports:
      - '8000:8000'

  db:
   image: postgres:12.0-alpine
   environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguserpw
      POSTGRES_DB: crud
   ports:
      - '5432:5432'
   volumes:
     - nps_data:/var/lib/postgresql/data
volumes:
   nps_data: {}


  
